### ISSUE TITLE
Error in Measure Notebook - 2.3 Format the log data - computation_func.py

### ISSUE THREAD

**Issue by libbyjenn97** [watson-developer-cloud/assistant-improve-recommendations-notebook#115]
The measure notebook suddenly stopped working for me in the 2.3 format the log data section in the extracting intents part of the code:
![Screen Shot 2021-07-13 at 11 34 33 AM](https://user-images.githubusercontent.com/29370743/125871173-29b53901-af2c-485f-8ddc-f4563db27f65.png)

I ended up taking out the response_dialog_request_counter and response_dialog_turn_counter columns to fix the error but would like to understand why it suddenly stopped working and if it's happening for others.

Thanks,
Libby

**Comment by libbyjenn97** [comment]
Just saw the commit that was made a couple of hours ago - I assume that's related to the issue I'm facing :)

**Comment by zairah10** [comment]
Hi @libbyjenn97 

There was a change to some of the V1 API fields returned that occurred on Mon Jul 12th, which resulted in certain fields that are marked as "Internal only" no longer be returned. This includes the fields highlighted :
response.context.system
'dialog_turn_counter'
'dialog_request_counter'
'dialog_stack'
https://cloud.ibm.com/apidocs/assistant/assistant-v1#message

These fields were however being referenced inside the toolkit which was causing the error that you reported. 

Could you please try running the notebook again? The issue has been resolved in the latest version of the toolkit.

**Comment by libbyjenn97** [comment]
Thanks @zairah10, just merged in the changes and it's working fine. I made a similar fix :) 

Thanks also for confirming what happened. Thought it was something to do with the API changing but couldn't find where that was referenced.

Thanks,
Libby
