### ISSUE TITLE
Handling 2 erros

### ISSUE THREAD

**Issue by miguelfaga** [watson-developer-cloud/assistant-improve-recommendations-notebook#19]
Hi there! I'm trying to run the Measure Notebook, but I'm having a couple of troubles. Firstly, in cell #6 (2.1.3), I get the 'NoneType' error while calling the get_logs() function. I'm just starting in Python so I can't be sure, but it seems the "project" key is missing in the project_creds dictionary.  So, when trying to call the .get_files() method in the project variable, I get a NoneType.  Any ideas on how to fix this?

Also, I can't plot the pie graphs for the overall metrics (4.1). I get a ValueError that says 'jpeg' is not supported. Is there any requirement I might be missing?

Thanks for your help!

**Comment by borseanand83** [comment]
Hi, I am having a similar issue as mentioned by @miguelfaga . is there any update on this? 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-23-7fa48315ff82> in <module>()
      4 
      5     # Send this info into the get_logs function
----> 6     project_creds={'project':project,'sdk_object':conversation, 'ws_id':workspace['workspace_id'], 'ws_name':workspace['name']}
      7 
      8     # Fetch the logs for the workspace

NameError: name 'project' is not defined
------------------------------------------------------------------------

**Comment by borseanand83** [comment]
Ended up using the get_logs_jupyter function from watson_assistant_func instead of the get_logs function. get_logs_jupyter function does not require project.
