### ISSUE TITLE
Watson-developer-cloud

### ISSUE THREAD

**Issue by miamanavalan** [watson-developer-cloud/assistant-improve-recommendations-notebook#20]
I continue to get this issue that there is no module named watson_developer_cloud 
<img width="784" alt="screen shot 2018-12-26 at 10 52 10 am" src="https://user-images.githubusercontent.com/46164405/50450488-69200e00-08fc-11e9-8614-f15cc0291a40.png">

**Comment by germanattanasio** [comment]
This happens when you don't have the SDK installed. Make sure you run `pip install watson-developer-cloud`.
