### ISSUE TITLE
Include pictures or a sample notebook so I know what I can expect

### ISSUE THREAD

**Issue by tomlroach** [watson-developer-cloud/assistant-improve-recommendations-notebook#21]
It would be valuable to include some screenshots or a link to a sample notebook in the description so I know what to expect before I go to the effort of setting this up.

**Comment by zzhang13** [comment]
The measure jupyter notebook (https://github.com/watson-developer-cloud/assistant-improve-recommendations-notebook/blob/master/notebook/Measure%20Notebook.ipynb) by default loads an example workspace and sample log data. It should produce results without any setup.
