### ISSUE TITLE
issue in effectiveness notebook running step 7 Summary and recommendation with sample data

### ISSUE THREAD

**Issue by themeichten** [watson-developer-cloud/assistant-improve-recommendations-notebook#25]
running the notebook in studio using provided sample annotation.xlsx file, and receive the following error:

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/pandas/core/ops.py:816: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)

thanks

**Comment by zzhangncsu** [comment]
Not seeing the error when running the Studio version (https://dataplatform.cloud.ibm.com/exchange/public/entry/view/133dfc4cd1480bbe4eaa78d3f636921c). Which environment are you using? Which step is causing this error? Thanks.

**Comment by themeichten** [comment]
using to online free studio edition Default Python 3.5 Free, 2 vCPU and 8 GB RAM,
