### ISSUE TITLE
ValueError in Measure Notebook step 4.1

### ISSUE THREAD

**Issue by cscottrun** [watson-developer-cloud/assistant-improve-recommendations-notebook#48]
Measure Notebook.ipynb step 4.1 Calculate overall metrics produces an error. 
I cloned the repo, installed the dependencies, and changed nothing within the notebook. I got the following error:

"ValueError: Format 'jpeg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)"

I found where visualize_func.py specifies fig.savefig(tmpfile, format='jpeg') (line 172) and changed to 'png'. But got the exact same error, suggesting that format is set to jpeg somewhere else.

**Comment by zzhang13** [comment]
@cscottrun The problem might be related to the version of `matplotlib` installed in your environment. Could you try running `pip freeze | grep matplotlib` in your terminal and check the version? You can update matplotlib to version 2.2.3 using `pip install matplotlib==2.2.3`

If the above solution is not working, you can try install `pillow` lib with `pip install pillow`.
