### ISSUE TITLE
Update to use latest version of Watson Python SDK

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/assistant-improve-recommendations-notebook#49]
The Watson Python SDK is up to 4.x now, this sample uses 1.x

**Comment by jsstylos** [comment]
@zzhang13

**Comment by zzhang13** [comment]
@jsstylos We are working on the updated version.

**Comment by zzhang13** [comment]
Notebooks have been updated to Watson Python SDK 4.1.0.
