### ISSUE TITLE
Error running 1.3 in Measure Notebook

### ISSUE THREAD

**Issue by vivianistan** [watson-developer-cloud/assistant-improve-recommendations-notebook#52]
I get this error when I try to run step 1.3 (Import functions used in the notebook) in the Measure Notebook: 

```
 File "visualize_func.py", line 147
    ax.text(0.5, -10, '±{0}'.format(round_decimal(var_prec, 1)), color='black', ha='center', va='center', fontsize=20)
                                                                                                                      ^
SyntaxError: Non-ASCII character '\xc2' in file visualize_func.py on line 147, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

**Comment by vivianistan** [comment]
I added ```# -*- coding: utf-8 -*-``` to the top of the `visualize_func.py` file and this seemed to fix the problem

**Comment by cclauss** [comment]
Are you using Python 2??

**Comment by vivianistan** [comment]
Yes, I'm using Jupyter with Python 2

**Comment by cclauss** [comment]
https://pythonclock.org

**Comment by vivianistan** [comment]
I see, I changed the Jupyter kernel to Python 3 since it was set to Python 2 by default and everything seems to work as expected. Thank you!
