### ISSUE TITLE
Error in 1.3 Import functions used in the notebook

### ISSUE THREAD

**Issue by vivianistan** [watson-developer-cloud/assistant-improve-recommendations-notebook#53]
I get this error when I run step 1.3: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-19-592057681eaa> in <module>()
     15 
     16 # Import Watson Assistant related functions
---> 17 from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
     18 from watson_assistant_func import get_logs_jupyter
     19 

ImportError: No module named authenticators
```

I've installed the latest version of ibm_cloud_sdk_core, so I'm not sure what the issue is?

**Comment by cclauss** [comment]
authenticators —> authenticator (drop the s)?

**Comment by vivianistan** [comment]
Changed to `authenticator` but I get a similar error: 
```
ImportError: No module named authenticator
```

**Comment by cclauss** [comment]
My mistake...  It is plural.  https://github.com/IBM/python-sdk-core/tree/master/ibm_cloud_sdk_core/authenticators. Are you sure that you have a current release https://github.com/IBM/python-sdk-core/releases ?

**Comment by vivianistan** [comment]
Related to https://github.com/watson-developer-cloud/assistant-improve-recommendations-notebook/issues/52, but when I switched my kernel from Python 2 to Python 3 this issue was resolved. Thank you!
