### ISSUE TITLE
not working with me

### ISSUE THREAD

**Issue by A7medFCIH** [watson-developer-cloud/assistant-improve-recommendations-notebook#82]
in this part of code, always show me 

RuntimeError: Error getting logs using API.  Please check if URL/credentials are correct.
![image](https://user-images.githubusercontent.com/22689845/86520975-dfcf8d00-be4a-11ea-8848-e7597eed3735.png)

**Comment by zzhang13** [comment]
@A7medFCIH Did you add the authentication info of your assistant in Section 2.1.1. The notebook needs API_KEY and URL.

<img width="1012" alt="Screen Shot 2020-07-13 at 1 57 40 PM" src="https://user-images.githubusercontent.com/43827532/87337058-d318fc00-c510-11ea-9a32-2feff21253fe.png">
