### ISSUE TITLE
Facing an error while running the measurement notebook.

### ISSUE THREAD

**Issue by surmar49** [watson-developer-cloud/assistant-improve-recommendations-notebook#84]
Hi @zzhang13 , 
I am facing the below error while running the measurement notebook. 
![image](https://user-images.githubusercontent.com/8286623/89645349-3bbc8400-d8d7-11ea-8ffb-59c157080c67.png)

Thanks.

**Comment by zzhang13** [comment]
The error seems to be caused by a lower version of pandas. The notebook uses pandas==1.0.3. Could you check if you have this version installed?

**Comment by surmar49** [comment]
@zzhang13 Yes, pandas==1.0.3 this is the version that is installed in the Measurement notebook.

**Comment by zzhang13** [comment]
Issue has been solved after installing pandas==1.0.3 then restart and clean the notebook
