### ISSUE TITLE
Error installing packages

### ISSUE THREAD

**Issue by maclean-stu** [watson-developer-cloud/assistant-improve-recommendations-notebook#85]
Attempting to run this notebook in Watson Studio in the Cloud I get errors attempting to install packages
![Screen Shot 2020-08-06 at 10 29 30 am](https://user-images.githubusercontent.com/14881465/89477206-02e5b780-d7d0-11ea-8c0b-fbfb071ff134.png)

/usr/bin/sh: pip3: command not found

**Comment by surmar49** [comment]
@maclean-stu 
You may check if pip installed on your machine. 
To check that, you can run this below command in your terminal 
>> pip3 --version

If pip3 is not installed, then you will need to install the pip3 and run the packages in the notebook.
>> python3 -m pip install --upgrade pip

**Comment by maclean-stu** [comment]
i am running this in Watson Studio on IBM Cloud. By default i think my environment has pip installed, should i change the code to use pip or install pip3?

**Comment by zzhang13** [comment]
@maclean-stu For Studio environment, please use the version in Studio gallery: https://dataplatform.cloud.ibm.com/exchange/public/entry/view/133dfc4cd1480bbe4eaa78d3f635e568

**Comment by maclean-stu** [comment]
Thanks. I was not aware they were in the Gallery. great work.
